name: Emscripten-CMake

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.37
        
      - name: Verify
        run: emcc -v

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd Comp-emscripten-glfw-opengles
          emcmake cmake .
          emmake make
          cd ../Comp-emscripten-glfw-opengles-imgui
          emcmake cmake .
          emmake make
          cd ../Comp-emscripten-sdl2-opengles
          emcmake cmake .
          emmake make
          cd ../Comp-emscripten-sdl2-opengles-imgui
          emcmake cmake .
          emmake make
