name: Node.js Wasm CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      node-version: 18.x
      steps:
        - uses: mymindstorm/setup-emsdk@v11
          with:
            version: 3.1.37
        - name: Verify
          run: emcc -v

        - uses: actions/checkout@v3

        - name: Build Wasm
          run: |
            cd Comp-emscripten-react
            emcmake cmake .
            emmake make

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
            cache-dependency-path: si-web-react/package-lock.json
        - run: npm install
          working-directory: ./si-web-react
        - run: npm run build --if-present
          working-directory: ./si-web-react