# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Wasm CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        #node-version: [ 14.x, 16.x, 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      steps:
        - uses: mymindstorm/setup-emsdk@v11
          with:
            version: 3.1.37
        - name: Verify
          run: emcc -v

        - uses: actions/checkout@v3

        - name: Build
          run: |
            cd Comp-emscripten-react
            emcmake cmake .
            emmake make

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
            cache-dependency-path: si-web-react/package-lock.json
        - run: npm install
          working-directory: ./si-web-react
        - run: npm run build --if-present
          working-directory: ./si-web-react