name: Node.js Wasm CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        #        node-version: [ 12.x, 14.x, 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.37

      - name: Verify Emscripten
        run: emcc -v

      - name: Build Wasm
        run: |
          cd Comp-emscripten-react
          emcmake cmake .
          emmake make

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies and Build
        run: |
          cd Comp-emscripten-react
          npm install
          npm run build --if-present
