name: Node.js Wasm CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
      steps:
        - name: Check out code
          uses: actions/checkout@v2

        - name: Setup Emscripten
          uses: mymindstorm/setup-emsdk@v1
          with:
            emscripten-version: 2.0.30

        - name: Verify Emscripten
          run: emcc -v

        - name: Build Wasm
          run: |
            cd Comp-emscripten-react
            emcmake cmake .
            emmake make

        - name: Setup Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install Dependencies and Build
          run: |
            cd si-web-react
            npm install
            npm run build --if-present
