name: Node.js Wasm CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ "14.x", "16.x", "18.x" ]
      steps:
        - uses: mymindstorm/setup-emsdk@v11
          with:
            version: 3.1.37
        - name: Verify
          run: emcc -v

        - uses: actions/checkout@v3

        - name: Build
          run: |
            cd Comp-emscripten-react
            emcmake cmake .
            emmake make

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore Dependencies
        run: npm ci
        working-directory: ./si-web-react

      - name: Build
        run: npm run build --if-present
        working-directory: ./si-web-react
